name: SEJA Trading Co
favicon: null
layout_spectrum: 0.49729
typography_spectrum: 0.68532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050707'
    - '#1d2f51'
    - '#848789'
    - '#474b4c'
  brandStrength: 0.8375256219878793
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
