name: SEJA Trading Co
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68532
title: 'SEJA Trading Company - Bringing you the best deals and savings!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050707'
    - '#1d2f51'
    - '#848789'
    - '#474b4c'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
