name: SEJA Trading Co
favicon: null
layout_spectrum: 0.48465
typography_spectrum: 0.85148
title: 'SEJA Trading Company - Sail the Seven Seas of Savings!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#050707'
    - '#90b2df'
    - '#718fb7'
    - '#39579d'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
